package com.example.UMS.features.common;

public enum Nationality {
    Afghan, Albanian, Algerian, American, Andorran, Angolan, Anguillan,
    Antigua_and_Barbuda, Argentine, Armenian, Australian, Austrian,
    Azerbaijani, Bahamian, Bahraini, Bangladeshi, Barbadian, Belarusian,
    Belgian, Belizean, Beninese, Bermudian, Bhutanese, Bolivian,
    Bosnia_and_Herzegovina, Botswanan, Brazilian, British, British_Virgin_Islander,
    Bruneian, Bulgarian, Burkinan, Burmese, Burundian, Cambodian, Cameroonian,
    Canadian, Cape_Verdean, Cayman_Islander, Central_African, Chadian, Chilean,
    Chinese, Colombian, Comoran, Congolese_Congo, Congolese_DRC, Cook_Islander,
    Costa_Rican, Croatian, Cuban, Cymraes, Cymro, Cypriot, Czech, Danish,
    Djiboutian, Dominican_Dominican_Republic, Dutch, East_Timorese, Ecuadorean,
    Egyptian, Emirati, English, Equatorial_Guinean, Eritrean, Estonian, Ethiopian,
    Faroese, Fijian, Filipino, Finnish, French, Gabonese, Gambian, Georgian,
    German, Ghanaian, Gibraltarian, Greek, Greenlandic, Grenadian, Guamanian,
    Guatemalan, Guinea_Bissau, Guinean, Guyanese, Haitian, Honduran, Hong_Konger,
    Hungarian, Icelandic, Indian, Indonesian, Iranian, Iraqi, Irish,
    Italian, Ivorian, Jamaican, Japanese, Jordanian, Kazakh, Kenyan, Kittitian,
    Kiribati, Kosovan, Kuwaiti, Kyrgyz, Lao, Latvian, Lebanese, Liberian, Libyan,
    Liechtenstein_citizen, Lithuanian, Luxembourger, Macanese, Macedonian,
    Malagasy, Malawian, Malaysian, Maldivian, Malian, Maltese, Marshallese,
    Martiniquais, Mauritanian, Mauritian, Mexican, Micronesian, Moldovan, Monegasque,
    Mongolian, Montenegrin, Montserratian, Moroccan, Mosotho, Mozambican, Namibian,
    Nauruan, Nepalese, New_Zealander, Nicaraguan, Nigerian, Nigerien, Niuean,
    North_Korean, Northern_Irish, Norwegian, Omani, Pakistani, Palauan, Palestinian,
    Panamanian, Papua_New_Guinean, Paraguayan, Peruvian, Pitcairn_Islander, Polish,
    Portuguese, Prydeinig, Puerto_Rican, Qatari, Romanian, Russian, Rwandan,
    Salvadorean, Sammarinese, Samoan, Sao_Tomean, Saudi_Arabian, Scottish,
    Senegalese, Serbian, Seychelles, Sierra_Leonean, Singaporean, Slovak,
    Slovenian, Solomon_Islander, Somali, South_African, South_Korean, South_Sudanese,
    Spanish, Sri_Lankan, St_Helenian, St_Lucian, Stateless, Sudanese, Surinamese,
    Swazi, Swedish, Swiss, Syrian, Taiwanese, Tajik, Tanzanian, Thai, Togolese,
    Tongan, Trinidadian, Tristanian, Tunisian, Turkish, Turkmen, Turks_and_Caicos_Islander,
    Tuvaluan, Ugandan, Ukrainian, Uruguayan, Uzbek, Vatican_citizen, Vanuatu,
    Venezuelan, Vietnamese, Vincentian, Wallisian, Welsh, Yemeni, Zambian, Zimbabwean
}
